on: 
  workflow_dispatch
jobs:
  build:
    name: Generate Exam
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create personalized exams
      run: python randomize_exam_template.py ${{ github.actor }}
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Created personalized exam" -a
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
